name:                free-algebras
version:             0.0.4.0
license:             MPL-2.0
license-file:        LICENSE
author:              "Marcin Szamotulski"
maintainer:          "profunctor@pm.me"
copyright:           "(c) 2018 Marcin Szamotulski"
github:              coot/free-algebras
homepage:            https://github.com/coot/free-algebras#readme
bug-reports:         https://github.com/coot/free-algebras/issues

extra-source-files:
  - ChangeLog.md
  - README.md

# Metadata used when publishing your package
synopsis:            Free algebras in Haskell.
category:            Algebra, Control, Monads

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        
  Universal algebra approach to free algebras including
  higher kinded algebraic structures like functors, applicative functors or
  monads.

default-extensions:
  ConstraintKinds
  DataKinds
  DeriveFunctor
  EmptyDataDecls
  FlexibleInstances
  FlexibleContexts
  KindSignatures
  InstanceSigs
  MultiParamTypeClasses
  OverloadedStrings
  PolyKinds
  RankNTypes
  ScopedTypeVariables
  TupleSections
  TypeApplications
  TypeFamilies

dependencies:
  - base >= 4.11 && < 5
  - constraints
  - containers
  - data-fix
  - dlist
  - free
  - groups
  - kan-extensions
  - mtl
  - natural-numbers
  - transformers

flags:
  develop:
    description: Set -Werror flag
    manual: true
    default: false

library:
  source-dirs: src
  when:
    - condition: flag(develop)
      then:
        ghc-options:
          - -Werror
          - -Wall
          - -Wincomplete-record-updates
          - -Wincomplete-uni-patterns
          - -Wredundant-constraints
          - -Wno-deprecations
      else:
        ghc-options:
          - -Wall
          - -Wincomplete-record-updates
          - -Wincomplete-uni-patterns
          - -Wredundant-constraints
          - -Wno-deprecations

tests:
  free-algebras-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - containers
      - free-algebras
      - hedgehog
