version: 2.1
defaults: &defaults
  docker:
    - image: nixorg/nix:circleci
      environment:
        - USER: coot
commands:
  setup:
    description: "setup environment"
    steps:
      - run:
          name: "nix"
          command: |
            nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
            nix-channel --update
      - run:
          name: "install"
          command: |
            nix-env -f "<nixpkgs>" -iA cachix -f https://cachix.org/api/v1/install
            nix-env -f "<nixpkgs>" -i openssh
            nix-env -f "<nixpkgs>" -i git
      - run:
          name: "cachix"
          command: |
            cachix use iohk
            cachix use free-algebras
      - checkout
  cachix-push:
    description: "cachix push"
    parameters:
      o:
        type: string
        default: "./result"
    steps:
      - run:
          name: "cachix push"
          command: cachix push free-algebras << parameters.o >>
jobs:
  GHC8102:
    <<: *defaults
    steps:
      - setup
      - run:
          name: "GHC 8.10.2"
          command: |
            nix-build -A free-algebras --argstr compiler ghc8102 -o result-fa
            nix-build -A free-algebras-examples --argstr compiler ghc8102 -o result-ex
      - cachix-push:
          o: "./result-fa"
      - cachix-push:
          o: "./result-ex"
  GHC884:
    <<: *defaults
    steps:
      - setup
      - run:
          name: "GHC 8.8.4"
          command: |
            nix-build -A free-algebras --argstr compiler ghc884 -o result-fa
            nix-build -A free-algebras-examples --argstr compiler ghc884 -o result-ex
      - cachix-push:
          o: "./result-fa"
      - cachix-push:
          o: "./result-ex"
  GHC865:
    <<: *defaults
    steps:
      - setup
      - run:
          name: "GHC 8.6.5"
          command: |
            nix-build -A free-algebras --argstr compiler ghc865 -o result-fa
            nix-build -A free-algebras-examples --argstr compiler ghc865 -o result-ex
      - cachix-push:
          o: "./result-fa"
      - cachix-push:
          o: "./result-ex"

workflows:
  build:
    jobs:
      - GHC8102
      - GHC884
      - GHC865
