name:                free-algebras
version:             0.1.0.0
github:              "git@github.com:coot/free-algebras"
license:             MPL-2.0
license-file:        ../LICENSE
author:              "Marcin Szamotulski"
maintainer:          "profunctor@pm.me"
copyright:           "BSD"

extra-source-files:
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/coot/algebra#readme>

default-extensions:
  ConstraintKinds
  DataKinds
  DeriveFunctor
  EmptyDataDecls
  FlexibleInstances
  FlexibleContexts
  KindSignatures
  InstanceSigs
  MultiParamTypeClasses
  OverloadedStrings
  PolyKinds
  RankNTypes
  ScopedTypeVariables
  TupleSections
  TypeApplications
  TypeFamilies

dependencies:
  - base >= 4.7 && < 5
  - free
  - kan-extensions
  - mtl

library:
  source-dirs: src

tests:
  algebra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
    dependencies:
      - containers
      - free-algebras
      - hedgehog
